- hosts: all
  user: root
  port: 22
  vars:
    epel: "http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
  tasks:
  - name: "install epel repository"
    yum: name={{epel}} state=present

